import type { UserRole } from "@/types";

/** Maps classified activities to real app routes */
export const ACTIVITY_ROUTE_MAP: Record<UserRole, Record<string, string>> = {
  guest: {
    "Search available rooms": "/reservations",
    "View room details": "/reservations",
    "Make bookings": "/reservations",
    "Modify bookings": "/reservations",
    "Cancel bookings": "/reservations",
    "Make online payments": "/payments",
    "View payment history": "/payments",
    "Download receipts": "/payments",
    "Request room service": "/services",
    "Request housekeeping": "/services",
    "Request maintenance assistance": "/services",
    "Create account": "/register",
    "Update profile": "/dashboard",
    "View booking history": "/reservations",
    "Manage preferences": "/ai-personalization",
    "Receive notifications": "/communications",
    "Receive booking confirmations": "/communications",
    "Communicate with hotel staff": "/communications",
  },
  receptionist: {
    "Create bookings": "/reservations",
    "Update bookings": "/reservations",
    "Cancel bookings": "/reservations",
    "Verify reservations": "/reservations",
    "Register guests": "/guests",
    "Verify guest identity": "/check-in-out",
    "Assign rooms": "/check-in-out",
    "Process check-ins": "/check-in-out",
    "Generate guest bills": "/check-in-out",
    "Verify payments": "/payments",
    "Process check-outs": "/check-in-out",
    "Release rooms": "/check-in-out",
    "View guest profiles": "/guests",
    "Update guest information": "/guests",
    "View guest history": "/guests",
    "Send notifications": "/communications",
    "Respond to guest inquiries": "/communications",
  },
  staff: {
    "View service requests": "/services",
    "Accept assigned tasks": "/services",
    "Update task status": "/services",
    "Complete service requests": "/services",
    "Clean rooms": "/services",
    "Update room status": "/services",
    "Report room conditions": "/services",
    "Receive maintenance requests": "/services",
    "Perform repairs": "/services",
    "Record maintenance actions": "/services",
    "Deliver requested services": "/services",
    "Update service completion records": "/services",
  },
  finance: {
    "Verify payments": "/payments",
    "Process refunds": "/payments",
    "Monitor transactions": "/payments",
    "Review invoices": "/check-in-out",
    "Manage financial records": "/payments",
    "Validate payment confirmations": "/payments",
    "Generate revenue reports": "/reports",
    "Generate payment reports": "/reports",
    "Monitor hotel income": "/reports",
    "Review financial transactions": "/payments",
    "Verify payment accuracy": "/payments",
  },
  management: {
    "Monitor hotel operations": "/dashboard",
    "Monitor room occupancy": "/reports",
    "Monitor service performance": "/services",
    "Analyze hotel performance": "/reports",
    "Review KPIs": "/reports",
    "Make strategic decisions": "/reports",
    "View dashboards": "/dashboard",
    "Generate reports": "/reports",
    "Analyze trends": "/reports",
    "Monitor staff performance": "/services",
    "Review service quality": "/services",
    "Monitor multiple branches": "/multi-hotel",
    "Compare branch performance": "/multi-hotel",
  },
  admin: {
    "Create users": "/user-management",
    "Update users": "/user-management",
    "Delete users": "/user-management",
    "Reset passwords": "/user-management",
    "Assign roles": "/user-management",
    "Manage permissions": "/security",
    "Control access rights": "/security",
    "Add rooms": "/multi-hotel",
    "Update room information": "/multi-hotel",
    "Configure hotel services": "/services",
    "Monitor login activities": "/security",
    "Review audit logs": "/security",
    "Configure authentication": "/security",
    "Enable OTP settings": "/security",
    "Configure system settings": "/security",
    "Manage payment integrations": "/payments",
    "Manage communication settings": "/communications",
    "Backup database": "/security",
    "Restore data": "/security",
    "Manage system recovery": "/security",
    "Monitor system performance": "/dashboard",
    "Resolve system issues": "/security",
  },
};

export function routeForActivity(role: UserRole, activity: string): string {
  return ACTIVITY_ROUTE_MAP[role][activity] ?? "/dashboard";
}
