import type { NavItem } from "@/types";

export const NAV_ITEMS: NavItem[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    path: "/dashboard",
    icon: "LayoutDashboard",
    module: 0,
    roles: ["admin", "management", "receptionist", "staff", "finance", "guest"],
    description: "Operational overview & KPIs",
  },
  {
    id: "reservations",
    label: "Reservations",
    path: "/reservations",
    icon: "CalendarCheck",
    module: 1,
    roles: ["admin", "management", "receptionist", "guest"],
    description: "Room booking & availability",
  },
  {
    id: "checkin",
    label: "Check-in / Out",
    path: "/check-in-out",
    icon: "DoorOpen",
    module: 2,
    roles: ["admin", "receptionist", "guest"],
    description: "Guest arrival, checkout request & departure",
  },
  {
    id: "guests",
    label: "Guest Management",
    path: "/guests",
    icon: "Users",
    module: 3,
    roles: ["admin", "management", "receptionist"],
    description: "Profiles, preferences & history",
  },
  {
    id: "ai",
    label: "AI Personalization",
    path: "/ai-personalization",
    icon: "Sparkles",
    module: 4,
    roles: ["admin", "management", "guest"],
    description: "Recommendations & behavior insights",
  },
  {
    id: "payments",
    label: "Payments",
    path: "/payments",
    icon: "CreditCard",
    module: 5,
    roles: ["admin", "finance", "receptionist", "guest"],
    description: "Paypack MoMo & transactions",
  },
  {
    id: "services",
    label: "Services",
    path: "/services",
    icon: "ConciergeBell",
    module: 6,
    roles: ["admin", "staff", "receptionist", "guest"],
    description: "Housekeeping & room service",
  },
  {
    id: "dining",
    label: "Dining & Menu",
    path: "/dining",
    icon: "UtensilsCrossed",
    module: 6,
    roles: ["admin", "management", "receptionist", "staff", "guest"],
    description: "Breakfast, lunch & dinner orders",
  },
  {
    id: "reports",
    label: "Reports & Analytics",
    path: "/reports",
    icon: "BarChart3",
    module: 7,
    roles: ["admin", "management", "finance", "receptionist", "staff"],
    description: "KPI dashboards, charts & branded report downloads",
  },
  {
    id: "user-management",
    label: "User Management",
    path: "/user-management",
    icon: "UserCog",
    module: 11,
    roles: ["admin"],
    description: "Staff accounts, roles & directory",
  },
  {
    id: "communications",
    label: "Communications",
    path: "/communications",
    icon: "MessageSquare",
    module: 8,
    roles: ["admin", "staff", "receptionist", "guest"],
    description: "Notifications & messaging",
  },
  {
    id: "feedback",
    label: "Feedback & Complaints",
    path: "/feedback",
    icon: "Star",
    module: 8,
    roles: ["admin", "management", "receptionist", "guest"],
    description: "Submit or review guest feedback",
  },
  {
    id: "multi-hotel",
    label: "Multi-Hotel",
    path: "/multi-hotel",
    icon: "Building2",
    module: 9,
    roles: ["admin"],
    description: "Branch control & consolidation",
  },
  {
    id: "security",
    label: "Security & Access",
    path: "/security",
    icon: "Shield",
    module: 10,
    roles: ["admin"],
    description: "Role activities, audit logs & access control",
  },
];

export const ROLE_LABELS: Record<string, string> = {
  admin: "System Administrator",
  management: "Hotel Manager",
  receptionist: "Receptionist",
  staff: "Hotel Staff",
  finance: "Finance Officer",
  guest: "Guest",
};
